
# model Layers width heads parameters
# tiny   4     384    6        39M
# Base   6     512    8        74M
# Small  12    768    12       244M
# Medium 24    1024   16       769M
# Large  32    1280   20       1550M


#batch_type: numel
#batch_bins: 10000000
batch_size: 25
accum_grad: 1
max_epoch: 40
patience: none
init: none
num_att_plot: 0

val_scheduler_criterion:
    - valid
    - total_loss
best_model_criterion:
-   - valid
    - total_loss
    - min
keep_nbest_models: 1

model_conf:
    report_cer: False
    report_wer: False
    output_dim: 1280


    #init_param: [
    #"pretrained/valid.loss.ave_10best.pth:encoder:encoder",

    #]
    #
freeze_param: [
    "frontend"
    ]

frontend: whisper
frontend_conf:
    whisper_model: large-v2
        
encoder: transformer
encoder_conf:
    output_size: 256
    attention_heads: 4
    linear_units: 512 
    num_blocks: 3
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.0
    input_layer: null
    normalize_before: true

optim: adam
optim_conf:
    lr: 0.025
    weight_decay: 0.000001
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 40000




  #specaug: specaug
  #specaug_conf:
  #apply_time_warp: true
  ## time_warp_window: 5
  #  time_warp_mode: bicubic
  #  apply_freq_mask: true
  #  freq_mask_width_range:
  #  - 0
  #  - 30
  #  num_freq_mask: 2
  #  apply_time_mask: true
  #  time_mask_width_range:
  #  - 0
  #  - 40
  #  num_time_mask: 2
