#batch_type: numel
#batch_bins: 10000000
batch_size: 32
accum_grad: 1
max_epoch: 80
patience: none
init: none
num_att_plot: 0

val_scheduler_criterion:
    - valid
    - total_loss
best_model_criterion:
-   - valid
    - total_loss
    - min
keep_nbest_models: 1

model_conf:
        #ctc_weight: 0.3
    report_cer: False
    report_wer: False

    #init_param: [
    #"pretrained/valid.loss.ave_10best.pth:encoder:encoder",

    #]
    #

encoder: transformer
encoder_conf:
    output_size: 32
    attention_heads: 4
    linear_units: 32 
    num_blocks: 1
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.0
    input_layer: null
    normalize_before: true

optim: adam
optim_conf:
    lr: 0.0015
    weight_decay: 0.000001
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 25000

frontend_conf:
  n_fft: 512
  hop_length: 160

  #specaug: specaug
  #specaug_conf:
  #apply_time_warp: true
  ## time_warp_window: 5
  #  time_warp_mode: bicubic
  #  apply_freq_mask: true
  #  freq_mask_width_range:
  #  - 0
  #  - 30
  #  num_freq_mask: 2
  #  apply_time_mask: true
  #  time_mask_width_range:
  #  - 0
  #  - 40
  #  num_time_mask: 2
