#batch_type: numel
#batch_bins: 10000000
batch_size: 32
accum_grad: 1
max_epoch: 20
patience: none
init: none
num_att_plot: 0

val_scheduler_criterion:
    - valid
    - mseloss
best_model_criterion:
-   - valid
    - mseloss
    - min
keep_nbest_models: 10

#model_conf:

    #init_param: [
    #"pretrained/valid.loss.ave_10best.pth:encoder:encoder",

    #]
encoder: conformer
encoder_conf:
    output_size: 512
    attention_heads: 8
    linear_units: 2048
    num_blocks: 3
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: conv2d
    normalize_before: true
    macaron_style: true
    rel_pos_type: latest
    pos_enc_layer_type: "rel_pos"
    selfattention_layer_type: "rel_selfattn"
    activation_type: "swish"
    use_cnn_module:  true
    cnn_module_kernel: 31



optim: adam
optim_conf:
    lr: 0.0015
    weight_decay: 0.000001
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 25000

frontend_conf:
  n_fft: 512
  hop_length: 160

  #specaug: specaug
  #specaug_conf:
  #apply_time_warp: true
  ## time_warp_window: 5
  #  time_warp_mode: bicubic
  #  apply_freq_mask: true
  #  freq_mask_width_range:
  #  - 0
  #  - 30
  #  num_freq_mask: 2
  #  apply_time_mask: true
  #  time_mask_width_range:
  #  - 0
  #  - 40
  #  num_time_mask: 2
